In [15]:
import pandas as pd

df = pd.read_csv("/Users/kousiknandury/Desktop/Spotify_demo/ml/data/songs.csv")

df.info()
df.head()
df.describe(include="all")

<class 'pandas.DataFrame'>
RangeIndex: 32833 entries, 0 to 32832
Data columns (total 23 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   track_id                  32833 non-null  str
 1   track_name                32828 non-null  str
 2   track_artist              32828 non-null  str
 3   track_popularity          32833 non-null  int64
 4   track_album_id            32833 non-null  str
 5   track_album_name          32828 non-null  str
 6   track_album_release_date  32833 non-null  str
 7   playlist_name             32833 non-null  str
 8   playlist_id               32833 non-null  str
 9   playlist_genre            32833 non-null  str
 10  playlist_subgenre         32833 non-null  str
 11  danceability              32833 non-null  float64
 12  energy                    32833 non-null  float64
 13  key                       32833 non-null  int64
 14  loudness                  32833 non-null  float64
 15  mode                      32833 non-null  int64
 16  speechiness               32833 non-null  float64
 17  acousticness              32833 non-null  float64
 18  instrumentalness          32833 non-null  float64
 19  liveness                  32833 non-null  float64
 20  valence                   32833 non-null  float64
 21  tempo                     32833 non-null  float64
 22  duration_ms               32833 non-null  int64
dtypes: float64(9), int64(4), str(10)
memory usage: 5.8 MB

,track_id,track_name,track_artist,track_popularity,track_album_id,track_album_name,track_album_release_date,playlist_name,playlist_id,playlist_genre,...,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,duration_ms
count,32833,32828,32828,32833.000000,32833,32828,32833,32833,32833,32833,...,32833.000000,32833.000000,32833.000000,32833.000000,32833.000000,32833.000000,32833.000000,32833.000000,32833.000000,32833.000000
unique,28356,23449,10692,NaN,22545,19743,4530,449,471,6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,7BKLCZ1jbUBVqRi2FVlTVw,Poison,Martin Garrix,NaN,5L1xcowSxwzFUSJzvyMp48,Greatest Hits,2020-01-10,Indie Poptimism,4JkkvMpVl4lSioqQjeAL0q,edm,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,10,22,161,NaN,42,139,270,308,247,6043,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,NaN,42.477081,NaN,NaN,NaN,NaN,NaN,NaN,...,5.374471,-6.719499,0.565711,0.107068,0.175334,0.084747,0.190176,0.510561,120.881132,225799.811622
std,NaN,NaN,NaN,24.984074,NaN,NaN,NaN,NaN,NaN,NaN,...,3.611657,2.988436,0.495671,0.101314,0.219633,0.224230,0.154317,0.233146,26.903624,59834.006182
min,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,...,0.000000,-46.448000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,4000.000000
25%,NaN,NaN,NaN,24.000000,NaN,NaN,NaN,NaN,NaN,NaN,...,2.000000,-8.171000,0.000000,0.041000,0.015100,0.000000,0.092700,0.331000,99.960000,187819.000000
50%,NaN,NaN,NaN,45.000000,NaN,NaN,NaN,NaN,NaN,NaN,...,6.000000,-6.166000,1.000000,0.062500,0.080400,0.000016,0.127000,0.512000,121.984000,216000.000000
75%,NaN,NaN,NaN,62.000000,NaN,NaN,NaN,NaN,NaN,NaN,...,9.000000,-4.645000,1.000000,0.132000,0.255000,0.004830,0.248000,0.693000,133.918000,253585.000000
max,NaN,NaN,NaN,100.000000,NaN,NaN,NaN,NaN,NaN,NaN,...,11.000000,1.275000,1.000000,0.918000,0.994000,0.994000,0.996000,0.991000,239.440000,517810.000000

In [18]:
df["playlist_genre"].value_counts()

playlist_genre
edm      6043
rap      5746
pop      5507
r&b      5431
latin    5155
rock     4951
Name: count, dtype: int64

In [20]:

df["playlist_subgenre"].value_counts().head(10)

playlist_subgenre
progressive electro house    1809
southern hip hop             1675
indie poptimism              1672
latin hip hop                1656
neo soul                     1637
pop edm                      1517
electro house                1511
hard rock                    1485
gangster rap                 1458
electropop                   1408
Name: count, dtype: int64

In [22]:
num_cols = [
 "danceability","energy","loudness","speechiness",
 "acousticness","instrumentalness","liveness",
 "valence","tempo","duration_ms","track_popularity"
]

df[num_cols].describe()

,danceability,energy,loudness,speechiness,acousticness,instrumentalness,liveness,valence,tempo,duration_ms,track_popularity
count,32833.000000,32833.000000,32833.000000,32833.000000,32833.000000,32833.000000,32833.000000,32833.000000,32833.000000,32833.000000,32833.000000
mean,0.654850,0.698619,-6.719499,0.107068,0.175334,0.084747,0.190176,0.510561,120.881132,225799.811622,42.477081
std,0.145085,0.180910,2.988436,0.101314,0.219633,0.224230,0.154317,0.233146,26.903624,59834.006182,24.984074
min,0.000000,0.000175,-46.448000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,4000.000000,0.000000
25%,0.563000,0.581000,-8.171000,0.041000,0.015100,0.000000,0.092700,0.331000,99.960000,187819.000000,24.000000
50%,0.672000,0.721000,-6.166000,0.062500,0.080400,0.000016,0.127000,0.512000,121.984000,216000.000000,45.000000
75%,0.761000,0.840000,-4.645000,0.132000,0.255000,0.004830,0.248000,0.693000,133.918000,253585.000000,62.000000
max,0.983000,1.000000,1.275000,0.918000,0.994000,0.994000,0.996000,0.991000,239.440000,517810.000000,100.000000

In [23]:
df[num_cols].corr()["track_popularity"].sort_values(ascending=False)

track_popularity    1.000000
acousticness        0.085159
danceability        0.064748
loudness            0.057687
valence             0.033231
speechiness         0.006819
tempo              -0.005378
liveness           -0.054584
energy             -0.109112
duration_ms        -0.143682
instrumentalness   -0.149872
Name: track_popularity, dtype: float64

In [24]:
import json

audio_cols = [
 "danceability","energy","loudness","speechiness",
 "acousticness","instrumentalness","liveness",
 "valence","tempo"
]

df["audio_features"] = df[audio_cols].to_dict(orient="records")